server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true
    liquibase:
      enabled: true
    git:
      enbled: true

logging:
  level.root: INFO
  level.io.fdlessard.codebites.order: DEBUG

spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false



